name: supported_devices_platform_interface
description: A common platform interface for the `supported_devices` plugin.
version: 0.0.1
homepage: https://github.com/SmitSonani
repository: https://github.com/SmitSonani/supported_devices/tree/main

publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.1

dev_dependencies:
  flutter_lints: ^1.0.4
