name: supported_devices
description: Flutter plugin to get the supported devices by the platform.
version: 0.0.1
homepage: https://github.com/SmitSonani
repository: https://github.com/SmitSonani/supported_devices/tree/main

publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  supported_devices_platform_interface:
    path: ../supported_devices_platform_interface
  supported_devices_ios:
    path: ../supported_devices_ios
  supported_devices_android:
    path: ../supported_devices_android
  supported_devices_macos:
    path: ../supported_devices_macos
  supported_devices_web:
    path: ../supported_devices_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      ios:
        default_package: supported_devices_ios
      android:
        default_package: supported_devices_android
      macos:
        default_package: supported_devices_macos
      web:
        default_package: supported_devices_web
