name: supported_devices_android
description: Android implementation of the supported_devices plugin
version: 0.0.1
homepage: https://github.com/SmitSonani
repository: https://github.com/SmitSonani/supported_devices/tree/main

publish_to: "none"

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.example.supported_devices_android
        pluginClass: SupportedDevicesAndroidPlugin
